.idea/.gitignore, .idea/Carbon-Tracker.iml, .idea/compiler.xml, .idea/dbnavigator.xml, .idea/gradle.xml, .idea/jarRepositories.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/CarbonTrackerApplication.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/controller/Controller.java
=> #1 establish: establish server

Server/carbonTracker/.gitignore, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/controller/Controller.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/dto/AptEnergyRequest.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/service/AptService.java
* 국토교통부_공동주택 에너지 사용 정보를 호출해 결과를 반환하는 api 추가
=> #4 feature: add aptenergy controller

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/controller/ApartmentController.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/dto/AptEnergyRequest.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/dto/AptListRequest.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/ApartmentService.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/dto/AptEnergyRequest.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/dto/AptListRequest.java
* aptList, aptEnergy에 대한 Controller, DTO, Service를 apartment 패키지로 이동
* dto에 Getter annotation 추가
=> #7 refactoring: refactor apt

Server/carbonTracker/build.gradle, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/controller/ApartmentController.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/ApartmentService.java
* 단지 목록 제공 서비스 API와 지도 검색 API를 사용해 단지 목록과 해당하는 좌표 얻는 Service 생성
=> #19 feature: create apt & coordinate by using apis

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/controller/ApartmentController.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/ApartmentService.java
* 현재 방식: String 으로 반환하고 있는 호출 결과(단지명, 단지코드, 도로명 주소, 법정동 주소)
* 새로운 방식: JSON 배열 반환
=> #24 feature: refactor aptlistall() response

Server/carbonTracker/build.gradle, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/ApartmentService.java
* 기존 방식 : csv 파일을 Filebeat가 읽어서 Logstash로 보내는 방식  
* 새로운 방식 : Kafka로 파이프라인 처리 후 Logstash로 보내는 방식
=> #20 feature: connect kafka to elastic stack

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/ApartmentService.java
* API 연결
* 주어진 단지의 가스 사용량 반환 서비스 구현
=> #28 feature: 국토교통 건물에너지정보 서비스 API

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/controller/ApartmentController.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptEnergyService.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptListService.java
* `AptListService`, `AptEnergyService` 로 Service 분리
=> #37 refactoring: apartmentservice 리팩토링

Server/carbonTracker/build.gradle, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/controller/ApartmentController.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/dto/AptListResponse.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/repository/AptListRepository.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptListService.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/configuration/ElasticConfiguration.java
* 단지 코드 기준으로 apt 인덱스 데이터 조회  
* 조회 값 유무에 따른 조건 처리 (cache)  
* Elasticsearch 내 중복 데이터 처리
=> #30 feature: elasticsearch 조회 기능 구현

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/dto/AptEnergyResponse.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/repository/AptEnergyRepository.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptEnergyService.java
* AptEnergyResponse DTO, AptEnergyRepository 생성  
* 단지 코드를 이용해 ES에서 도로명주소, 법정동코드 조회  
* DB에 해당 단지 코드, 발생년월의 데이터가 있으면 API 호출 없이 DB에서 바로 값 조회
=> #36 feature: AptEnergy 서비스 ES 연동

Server/carbonTracker/build.gradle, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/appconfig/SwaggerConfig.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/controller/ApartmentController.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptEnergyService.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptListService.java
=> #35 feature: swagger ui 설정

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptEnergyService.java
* 도로명주소로부터 번, 지를 얻어 오는 것이 아닌 법정동주소로부터 번, 지를 얻어와 API 호출하는 방식으로 Bug fix
=> #39 bug: 가스 사용량 정보 조회 bug

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptEnergyService.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/config/ElasticConfiguration.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/config/WebConfig.java
* CORS 설정  
* aptEnergyAll에서 반복문 끝나지 않는 문제 해결
=> #41 bug: CORS 및 AptEnergy 에러

client/package-lock.json, client/package.json, client/src/App.js, client/src/api/index.js, client/src/atoms/index.js, client/src/components/MapArea.js, client/src/components/SearchBar.js, client/src/controllers/map.js, client/src/utils/findMatches.js, client/src/utils/http.js
- Recoil을 통해 주택 단지 정보 저장
- fetch에 대한 인터페이스, API 생성
- 카카오 맵에 주택 단지 마커로 표시, 클러스터링
- 검색창과 주택단지 정보 연동
=> Feat/issue 17/set kakaomap

client/src/App.js, client/src/atoms/index.js, client/src/controllers/map.js, client/src/utils/findMatches.js
=> #51 feat: 주택단지 데이터 캐싱

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptEnergyService.java
사용하는 두 개의 가스 사용량 API 단위 $m^3$로 통일
=> #60 bug: aptenergyservice 가스 사용량 단위 조정

client/src/components/EnergyChart.js, client/src/components/Modal.js, client/src/utils/createEnergyChart.js, client/src/utils/processEnergyData.js, client/src/utils/updateEnergyChart.js
- 결측치 데이터 대체 알고리즘 오류 수정
- 반환된 에너지 사용량이 전부 결측치인 경우 예외 처리
=> #57 fix: 에너지 사용량 결측치 알고리즘 버그 수정

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptEnergyService.java
* 단지코드와 현재년월을 입력받아 최근 2년간 날짜 배열 생성
* 현재년월 기준 최근 2년간의 data에 대한 사용량을 조회
=> #59 feature: aptenergyservice 수정

ML/.idea/.gitignore, ML/.idea/CarbonTracker.iml, ML/.idea/inspectionProfiles/profiles_settings.xml, ML/.idea/misc.xml, ML/.idea/modules.xml, ML/.idea/vcs.xml, ML/main.py, ML/test_main.http
- 전기, 가스 사용량 & 기후 공공데이터 전처리
- 전기 사용량 예측 모델 학습
- 가스 사용량 예측 모델 학습
- FastAPI 환경 설정
=> #65 feature: 기후 데이터를 통한 예상 탄소 배출량 예측 모델

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptEnergyService.java
* 현재년월을 입력받아, 상,하반기하여 날짜 배열을 생성
* 과거 1년 전까지의 상(하)반기 사용량을 ES로부터 조회
* 21년 상(하)반기 사용량과 22년 상(하)반기까지의 사용량을 비교하여 감축률 계산
* 감축률에 따른 포인트 계산
* 데이터 자체의 문제로 인해 포인트 집계가 매우 불완전
* 결측치 처리 로직 필요
=> #58 feature: 예상 탄소 포인트 계산 service

client/src/api/index.js, client/src/components/CarbonPoint.js, client/src/components/Modal.js, client/src/components/common/Spinner.js, client/src/utils/getCurrentDate.js, client/src/utils/processEnergyData.js
=> #85 feat: 에너지 차트 로딩 구현

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/dto/AptListResponse.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptEnergyService.java, Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/CommonService.java
결측치 처리를 위해 결측치가 발생하는 연월에 대한 기상 정보를 조회하는 API 추가
=> #84 feature: 결측치 처리 service

client/src/api/index.js, client/src/components/Modal.js
- 에너지 사용량 데이터 sessionStorage 캐싱
=> #53 feat: 에너지 사용량 데이터 캐싱

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptEnergyService.java
* 결측치 처리 Service 사용 시 가스 사용량 값이 매우 크게 나오는 경우에 대해 `/ 10` 연산 수행
=> #94 bug: 결측치 처리 service 예외 처리

Server/carbonTracker/src/main/java/capstoneDesign/carbonTracker/apartment/service/AptEnergyService.java
* 결측치 처리 사용 시, 가스 사용량 단위 변환을 위한 `0.09` 곱셈
=> #96 feature: 결측치 처리 service 수정

client/src/api/index.js, client/src/components/CarbonPoint.js, client/src/components/EnergyChart.js, client/src/components/Modal.js, client/src/components/TodayCarbon.js, client/src/components/common/PredictBox.js, client/src/utils/processEnergyData.js
- 예상 탄소 배출량 컴포넌트 생성
- 예상 탄소 포인트 컴포넌트 생성
- 각 API 연동
=> #88 feat: 예상 탄소 배출량 및 탄소 포인트 컴포넌트 구현/배치
